### ISSUE TITLE
Need CI that starts with a running kube cluster

### ISSUE THREAD

**Issue by deads2k** [openshift/service-serving-cert-signer#8]
I need e2e tests that start with "here is a cluster-admin kubeconfig to a running kube-only cluster".  `oc cluster up --kube-only` can do this today.

As a concrete test of it today, the first thing I would try is

```
oc cluster up --kube-only
oc auth reconcile -f install/serving-cert-signer/install-rbac.yaml
oc create -f manifests/v3.10.0/service-serving-cert-signer-controller/clusterrole.yaml
oc create -f manifests/v3.10.0/service-serving-cert-signer-controller/clusterrolebinding.yaml
oc apply -f install/serving-cert-signer/install.yaml

// TODO call a serial e2e suite
```

@stevekuznetsov what would it take to get that?

**Comment by deads2k** [comment]
> /cc @smarterclayton
> 
> We will support this very soon. What's your timeline?

This week.  I'm approaching a level of complexity that needs e2e.

**Comment by stevekuznetsov** [comment]
I think we can make that happen this week.

**Comment by stevekuznetsov** [comment]
@smarterclayton candidate for a project to move to `ci-operator`?

**Comment by mrogers950** [comment]
We should close this issue, e2e testing will be done with ci-operator/origin conformance suite
